#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use MUONLINECORE\WPSP;
use MUONLINECORE\routes\Actions;
use MUONLINECORE\routes\AdminPages;
use MUONLINECORE\routes\Ajaxs;
use MUONLINECORE\routes\Apis;
use MUONLINECORE\routes\Filters;
use MUONLINECORE\routes\MetaBoxes;
use MUONLINECORE\routes\NavLocations;
use MUONLINECORE\routes\PostTypeColumns;
use MUONLINECORE\routes\PostTypes;
use MUONLINECORE\routes\RewriteFrontPages;
use MUONLINECORE\routes\WPRoles;
use MUONLINECORE\routes\Schedules;
use MUONLINECORE\routes\Shortcodes;
use MUONLINECORE\routes\Taxonomies;
use MUONLINECORE\routes\TaxonomyColumns;
use MUONLINECORE\routes\ThemeTemplates;
use MUONLINECORE\routes\UserMetaBoxes;

define('MUOC_START', microtime(true));

require_once __DIR__ . '/ArtisanHelpers.php';
$ensureDBConnect = ensureDBConnect();

if ($ensureDBConnect) {
    if (file_exists(__DIR__ . '/../../../wp-load.php')) {
        require_once __DIR__ . '/../../../wp-load.php';

        if (function_exists('is_plugin_active')) {
            /**
             * Kiểm tra plugin đã được kích hoạt hay chưa.\
             * Khi plugin đã được kích hoạt và hoạt động thành công\
             * thì "artisan" (hay môi trường terminal) sẽ hoạt động với:
             * - Full tính năng của WordPress.
             * - Full tính năng của tất cả plugin đang hoạt động.
             * - Full tính năng của plugin này.
             */
            $pluginDir      = plugin_dir_path(__FILE__);
            $pluginDirName  = plugin_basename($pluginDir);

            if (is_plugin_active($pluginDirName . '/main.php')) {
                define('MUOC_ACTIVE', true);
            }
            else {
                echo "------------------------------------\n";
                echo "\033[32m[✓] Bạn đang chạy \"artisan\" trong môi trường WordPress!\033[0m\n";
                echo "\033[33m[!] Vui lòng kích hoạt plugin để sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
                echo "------------------------------------\n";
            }
        }
        else {
            echo "------------------------------------\n";
            echo "\033[31m[X] Bạn đang chạy \"artisan\" trong môi trường không phải WordPress!\033[0m\n";
            echo "\033[31m[X] Có thể bạn sẽ không được sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
            echo "\033[33m[!] Vui lòng kích hoạt plugin để sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
            echo "------------------------------------\n";
        }
    }
    else {
        echo "------------------------------------\n";
        echo "\033[31m[X] Bạn đang chạy \"artisan\" trong môi trường không phải WordPress!\033[0m\n";
        echo "\033[31m[X] Có thể bạn sẽ không được sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
        echo "\033[33m[!] Vui lòng kích hoạt plugin để sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
        echo "------------------------------------\n";
    }
}
else {
    echo "------------------------------------\n";
    echo "\033[31m[X] Bạn đang chạy \"artisan\" trong môi trường không phải WordPress!\033[0m\n";
    echo "\033[31m[X] Có thể bạn sẽ không được sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
    echo "\033[33m[!] Vui lòng kết nối database và kích hoạt plugin để sử dụng đầy đủ tính năng của \"artisan\"!\033[0m\n";
    echo "------------------------------------\n";
}

/**
 * Load composer autoload.
 */
require __DIR__ . '/vendor/autoload.php';

/**
 * ---
 * Start application.
 */
$wpsp = WPSP::startConsole();

/**
 * ---
 * Đăng ký routes.
 */
if (defined('MUOC_ACTIVE') && MUOC_ACTIVE) {
    foreach ([
        WPRoles::class,
        Apis::class,
        Ajaxs::class,
        Schedules::class,
        PostTypes::class,
        PostTypeColumns::class,
        MetaBoxes::class,
        ThemeTemplates::class,
        Taxonomies::class,
        TaxonomyColumns::class,
        Shortcodes::class,
        AdminPages::class,
        NavLocations::class,
        UserMetaBoxes::class,
        RewriteFrontPages::class,
        Actions::class,
        Filters::class,
    ] as $route) {
        (new $route())->register();
    }
}

/**
 * ---
 * Xử lý command line.
 */
$app    = $wpsp->getApplication();
$status = $app->handleCommand(new ArgvInput);
exit($status);